theme: jekyll-theme-cayman
title: Georeferencing Guide for OSU Maps and Spatial Data Employees
description: We love georeferencing, don't we folks?
level: Intermediate
repository: okstate-maps/mapsok
